spring.application.name=portfolio-backend

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.datasource.hikari.maximun-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always